steps:
    - group: ":buildkite: :mac: :coverage: Static Analysis"
      key: "static-analysis"
      steps:
          - label: ":testobject: cppcheck"
            command: "cppcheck src/"
          - label: ":cmake: clang-format"
            command: "fd --extension cc --extension h --exec clang-format -style=Google"
          - label: ":repolinter: trunk check --ci"
            command: "trunk check"
    - label: ":buildkite: :bazel: :mac: bazel build //..."
      command: "bazel build //..."
    - label: ":buildkite: :bazel: :mac: :test_tube: bazel test //..."
      command: "bazel test -- //... -:requirements_test" # exclude requirements_test (currently broken)
