name: CI (bazel build //...; bazel test //...)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Bazelisk
              uses: bazelbuild/setup-bazelisk@v2

            - name: Mount Bazel Cache
              uses: actions/cache@v3
              with:
                  path: '~/.cache/bazel'
                  key: bazel

            - name: Bazel Build
              run: bazel build ...

            - name: Unit tests
              run: bazel test ...
