name: CI (trunk check)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Trunk Check
              uses: trunk-io/trunk-action@v1
